# Reference https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.webapp.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.webapp.name }}
  minReplicas: {{ .Values.webapp.autoscale.minReplicaCount }}
  maxReplicas: {{ .Values.webapp.autoscale.maxReplicaCount }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: {{ .Values.webapp.autoscale.cpuAverageUtilization }}
